version: '3.9'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

services:
  postgres-instance:
    restart: unless-stopped
    image: postgres:latest
    container_name: postgres-instance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis-instance:
    restart: unless-stopped
    image: redis:latest
    container_name: redis-instance
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
